"""
Static reference data for the dashboard: franchise background info and
home-stadium details. These are stable historical facts (founding year,
home city/ground, IPL titles won through the 2025 season) — not things the
live model predicts.
"""

TEAM_INFO = {
    "Chennai Super Kings": {
        "short": "CSK",
        "color": "#F9CD05",
        "text_color": "#0b0b0b",
        "founded": 2008,
        "home_ground": "MA Chidambaram Stadium, Chepauk, Chennai",
        "city": "Chennai",
        "titles": 5,
        "title_years": [2010, 2011, 2018, 2021, 2023],
    },
    "Mumbai Indians": {
        "short": "MI",
        "color": "#004BA0",
        "text_color": "#ffffff",
        "founded": 2008,
        "home_ground": "Wankhede Stadium, Mumbai",
        "city": "Mumbai",
        "titles": 5,
        "title_years": [2013, 2015, 2017, 2019, 2020],
    },
    "Kolkata Knight Riders": {
        "short": "KKR",
        "color": "#3A225D",
        "text_color": "#ffffff",
        "founded": 2008,
        "home_ground": "Eden Gardens, Kolkata",
        "city": "Kolkata",
        "titles": 3,
        "title_years": [2012, 2014, 2024],
    },
    "Royal Challengers Bengaluru": {
        "short": "RCB",
        "color": "#EC1C24",
        "text_color": "#ffffff",
        "founded": 2008,
        "home_ground": "M Chinnaswamy Stadium, Bengaluru",
        "city": "Bengaluru",
        "titles": 1,
        "title_years": [2025],
    },
    "Delhi Capitals": {
        "short": "DC",
        "color": "#17479E",
        "text_color": "#ffffff",
        "founded": 2008,
        "home_ground": "Arun Jaitley Stadium, Delhi",
        "city": "Delhi",
        "titles": 0,
        "title_years": [],
    },
    "Punjab Kings": {
        "short": "PBKS",
        "color": "#ED1B24",
        "text_color": "#ffffff",
        "founded": 2008,
        "home_ground": "Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh",
        "city": "Mohali / New Chandigarh",
        "titles": 0,
        "title_years": [],
    },
    "Rajasthan Royals": {
        "short": "RR",
        "color": "#EA1A85",
        "text_color": "#ffffff",
        "founded": 2008,
        "home_ground": "Sawai Mansingh Stadium, Jaipur",
        "city": "Jaipur",
        "titles": 1,
        "title_years": [2008],
    },
    "Sunrisers Hyderabad": {
        "short": "SRH",
        "color": "#FF822A",
        "text_color": "#0b0b0b",
        "founded": 2012,
        "home_ground": "Rajiv Gandhi International Stadium, Uppal, Hyderabad",
        "city": "Hyderabad",
        "titles": 1,
        "title_years": [2016],
    },
    "Gujarat Titans": {
        "short": "GT",
        "color": "#1B2133",
        "text_color": "#ffffff",
        "founded": 2022,
        "home_ground": "Narendra Modi Stadium, Ahmedabad",
        "city": "Ahmedabad",
        "titles": 1,
        "title_years": [2022],
    },
    "Lucknow Super Giants": {
        "short": "LSG",
        "color": "#0057E2",
        "text_color": "#ffffff",
        "founded": 2022,
        "home_ground": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
        "city": "Lucknow",
        "titles": 0,
        "title_years": [],
    },
}

# Venue -> approximate seating capacity (publicly known, approximate figures)
STADIUM_CAPACITY = {
    "MA Chidambaram Stadium, Chepauk, Chennai": 38000,
    "Wankhede Stadium, Mumbai": 33000,
    "Eden Gardens, Kolkata": 68000,
    "M Chinnaswamy Stadium, Bengaluru": 40000,
    "Arun Jaitley Stadium, Delhi": 41000,
    "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": 26000,
    "Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh": 32000,
    "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur": 32000,
    "Sawai Mansingh Stadium, Jaipur": 30000,
    "Rajiv Gandhi International Stadium, Uppal, Hyderabad": 55000,
    "Narendra Modi Stadium, Ahmedabad": 132000,
    "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow": 50000,
    "Dr DY Patil Sports Academy, Mumbai": 55000,
    "Brabourne Stadium, Mumbai": 20000,
    "Maharashtra Cricket Association Stadium, Pune": 37000,
    "Himachal Pradesh Cricket Association Stadium, Dharamsala": 23000,
    "Barsapara Cricket Stadium, Guwahati": 40000,
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam": 27500,
    "Dubai International Cricket Stadium": 25000,
    "Sharjah Cricket Stadium": 17000,
    "Zayed Cricket Stadium, Abu Dhabi": 20000,
}
